# This is a basic workflow to help you get started with Actions

name: manually:0.0

on:
  workflow_dispatch:

jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/creml:2020.0
      volumes:
        - ${{ github.workspace }}/3.5.2023:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
        run: (python3 TorchConFoBi.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: '3.5.2023/results_torch.png'
          tag_push: '--force'
