# This is a basic workflow to help you get started with Actions

name: pytorch:0.0

on:
  workflow_dispatch:

jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/crecoding:2020.0
      volumes:
        - ${{ github.workspace }}/3.5.2023:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
      - name: cd pwd
        run: (pwd)
      - name: cd /cre/python/
        run: (cd /cre/python)
      - name: ls -l
        run: (ls -l)
      - name: Install pytorch
        run: (pip3 install torch)
      - name: Run TorchConFoBi
        run: (python3 ./3.5.2023/TorchConFoBi.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: '3.5.2023/results_torch.png'
          tag_push: '--force'
